INSERT INTO User VALUES (2, "뽀로로", 4, 0, "", "");
INSERT INTO User VALUES (3, "패티", 4, 0, "", "");
INSERT INTO User VALUES (4, "해리", 4, 0, "", "");
INSERT INTO User VALUES (5, "에디", 4, 0, "", "");
INSERT INTO User VALUES (6, "로보", 4, 0, "", "");
INSERT INTO User VALUES (7, "크롱", 4, 0, "", "");
INSERT INTO User VALUES (8, "시현", 4, 0, "", "");
INSERT INTO User VALUES (9, "bigsun", 4, 0, "", "");
INSERT INTO User VALUES (10, "intellijang", 4, 0, "", "");
